[package]
name = "cookbook"
version = "0.1.0"
authors = ["blackanger <blackanger.z@gmail.com>"]

[dependencies]
rand = "0.3.15"
regex = "0.2.2"

[lib]
name = "cookbook"
path = "src/lib.rs"

[[bin]]
name = "cookbook"
path = "src/bin.rs"
